name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: @actions/checkout@3
      - uses: actions/setup-node@v3

      - run: npm i
      - run: npm run ci
